server.port=8081
server.servlet.context-path=/coatingbazar
spring.application.name=coating-bazaar-api

# MailHog SMTP configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Default sender used by EmailService
app.mail.from=no-reply@coatingbazaar.com

